export { AirplaneIcon } from './AirplaneIcon'
export { HelicopterIcon } from './HelicopterIcon'
export { RocketIcon } from './RocketIcon'
export { UFOIcon } from './UFOIcon'
export { PlayerIcon } from './PlayerIcon'
