name: Prepare Build Environment

on:
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node.js + Yarn 缓存
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # 3️⃣ Java 缓存
      - name: Cache Java
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/Java_Temurin
          key: java-17-temurin-${{ runner.os }}
          restore-keys: java-17-temurin-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4️⃣ Android SDK 缓存
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            /opt/android-sdk
            ~/.android
          key: android-sdk-34-${{ runner.os }}
          restore-keys: android-sdk-34-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Accept Android licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # 5️⃣ Expo CLI 缓存
      - name: Cache Expo CLI
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.expo
          key: expo-${{ runner.os }}-${{ hashFiles('app.json', 'app.config.*') }}
          restore-keys: expo-${{ runner.os }}-

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # 6️⃣ 缓存依赖
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: deps-${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}
